### ISSUE TITLE
シェーマ画像の編集ができない。

### ISSUE THREAD

**Issue by PorcoRossoGitanes** [shokokb/eyeehr#16]
保存したシェーマ画像を読み出しても編集ができない。（ただし、表示はできている。）
読み出す際に、エラーとなる。
また、シェーマ画像のコピーが出来ると良い。（希望）
![image](https://cloud.githubusercontent.com/assets/8413071/5483689/504ee7f2-86ba-11e4-8a37-38a7025b3a47.png)

**Comment by shokokb** [comment]
（１）保存したシェーマ画像を読み出しても編集ができない。
　エラーの原因はSVG画像の作りによるため、該当箇所を変更する予定。
（２）シェーマ画像のコピーが出来ると良い。
　→どのような用途で使用するか、確認する。

**Comment by shokokb** [comment]
リオープン時、ハッチングデータを一時的に削除するように変更した。
さらに、保存時にハッチングデーターが追加される。
