### ISSUE TITLE
スタンプ管理

### ISSUE THREAD

**Issue by shokokb** [shokokb/eyeehr#19]
（１）スタンプ一覧画面
　（１−１）スタンプの新規追加...OK
　（１−２）スタンプの編集→（低）
　　OrcaItemの追加・削除...削除未済
　（１−３）スタンプの削除→（低）対応後回し
（２）スタンプ詳細画面
　（２−１）スタンプ名・スタンプ種類（色分け）・初期表示登録...OK
　（２−２）ORCA点数登録→追加・数量変更・削除
　　→数量は適宜変更されるので、そのままでよい。
　（２−３）保存・スタンプ一覧画面に戻る。...OK

**Comment by shokokb** [comment]
→Stamp 備考自動セット
→Orca部分編集用スタンプ（OrcaStamp）
→サイン機能（RemarkStamp）

**Comment by PorcoRossoGitanes** [comment]
この機能は、完成しました。
