### ISSUE TITLE
ファイルを添付しようとするとエラーとなる。（続き）

### ISSUE THREAD

**Issue by PorcoRossoGitanes** [shokokb/eyeehr#22]
主訴の入力で試しているが、１つ目の主訴では正常に添付出来るが、二つ目ではできない。
１つ目で添付できているファイルが２つ目では添付できない。

**Comment by shokokb** [comment]
> /**
>  * バイナリーファイル（画像等）をアップロードする。
>  * @param {String} i_id フォームID(<form />)
>  * @return 成功時、バイナリーファイルへのRESTパス。失敗時、空文字列。
>  */
> Utility.UploadBinFile = function (i_id) {
> 
>     var ret = '';
> 
>     $form = $('form#' + i_id);
→i_id=attachFile（固定）のため、画面全体のフォームが検出されてしまう。
> 
>     if ($form.length > 0)
→上記のlengthが1を超過していると保存に失敗する。
