### ISSUE TITLE
視力入力機能を追加する。

### ISSUE THREAD

**Issue by shokokb** [shokokb/eyeehr#27]
（１）モックアップを作製する。

**Comment by shokokb** [comment]
（１）視力保存
（２）さくらシステムへの連動
（３）ペアリング→OK
（４）経過グラフ化

**Comment by PorcoRossoGitanes** [comment]
検査項目から視力入力画面に移り、視力を入力後、式が検査項目に表示され得るようにする。

**Comment by PorcoRossoGitanes** [comment]
視力入力機能のみ実装
さくらシステム連動、グラフ作成は別
