### ISSUE TITLE
検査者を判別できるようにしたい。

### ISSUE THREAD

**Issue by shokokb** [shokokb/eyeehr#4]
→カルテは医師のみ記載可。
→医師以外はサインを残せるようにする。備考の最後に追加する？
→検査日時を設定できるようにする。

**Comment by shokokb** [comment]
→検査日時を設定できるようにする。

**Comment by PorcoRossoGitanes** [comment]
検査者のスタンプを登録できるようになりました。
このスタンプを押すことで、検査者を判別できるようになりました。
