### ISSUE TITLE
備考入力は、保存ボタンを押した時点で、ウインドウを閉じたほうが良い。

### ISSUE THREAD

**Issue by PorcoRossoGitanes** [shokokb/eyeehr#45]
![image](https://cloud.githubusercontent.com/assets/8413071/6386130/af424e5a-bdb7-11e4-9381-eaffd36f1581.png)

**Comment by shokokb** [comment]
記録ボタンで、カルテ画面に文字列を送信後、ウィンドウを閉じるように変更した。
