### ISSUE TITLE
シェーマで、文字を入力すると、選択ツールに戻ってしまう。文字入力ツールを連続で使えるようにしたい。

### ISSUE THREAD

**Issue by PorcoRossoGitanes** [shokokb/eyeehr#46]
![image](https://cloud.githubusercontent.com/assets/8413071/6386146/e200bd54-bdb7-11e4-8b43-008eff98b5ca.png)

**Comment by shokokb** [comment]
MethodDrawの使用上難しい。

**Comment by PorcoRossoGitanes** [comment]
不対応
