### ISSUE TITLE
スタンプの一番下が切れてしまう。→実装済、調整依頼

### ISSUE THREAD

**Issue by PorcoRossoGitanes** [shokokb/eyeehr#47]
スタンプ一覧がウインドウサイズの変更に対応していない為、下の方のスタンプが使えなくなる。

**Comment by shokokb** [comment]
To:PorcoRossoGitanes
configure.jsonのjson.StampList.Layout.heightを変更して高さを調整してください。

**Comment by PorcoRossoGitanes** [comment]
完了
