### ISSUE TITLE
病歴を患者マスター側に移動する。初診登録未済。

### ISSUE THREAD

**Issue by PorcoRossoGitanes** [shokokb/eyeehr#51]
患者マスタに、病歴の管理部分（保存先）を移動する。
また、転帰の入力ができるようにし、ORCAにも転帰情報を送る。
最初に病歴を登録する場合は、初診料を取るように、ORCAに情報を送る。
病歴は、登録してから、転帰で治癒、死亡、中止までを１つと考え、同じ病歴で来院した場合、前述の転帰で終了していた場合は、初診と考える。

**Comment by shokokb** [comment]
病名登録＆ORCA送信まで作成した。

**Comment by PorcoRossoGitanes** [comment]
完了しました。
