### ISSUE TITLE
タブレット対応（まず、検査入力のみ対応）

### ISSUE THREAD

**Issue by PorcoRossoGitanes** [shokokb/eyeehr#56]
それぞれの項目について、参照や編集が出来るようにしたいが、PC用とタブレット用で、環境が多少異なるため、それにあわせる作業が必要となる。

**Comment by shokokb** [comment]
ORCA連携部分、シェーマツール、未対応

**Comment by PorcoRossoGitanes** [comment]
タブレットで写真撮影機能をフルに使う。
