### ISSUE TITLE
病名・患者病名で添付ファイルが貼付けられない→修正済み、検収お願いします。

### ISSUE THREAD

**Issue by shokokb** [shokokb/eyeehr#75]

**Comment by shokokb** [comment]
（１）NoteItemContainerXXXにdata-collection属性を設置する。
（２）Noteのdata-collectionを廃止する。
（３）Note Patient Date Timeをdata-属性に持たせる。

**Comment by PorcoRossoGitanes** [comment]
後回し

**Comment by PorcoRossoGitanes** [comment]
修正を確認しました。
